### ISSUE TITLE
all functions works only for s161-de

### ISSUE THREAD

**Issue by destroyer92** [PiecePaperCode/pyogame2#1]
for the following functions the session.get is forced to 's161-de'
- get_resources()
- get_supply()
- get_facilities()
- get_research()
- get_ships()
- get_defences()
- get_galaxy()
- get_ally()
- send_message()
- send_fleet()

**Comment by PiecePaperCode** [comment]
MB didn't check the URL's itself. fixed it with format.(server_number, server_language)
pls try again

**Comment by destroyer92** [comment]
it works
