### ISSUE TITLE
Wrong Code in Wiki Snippets

### ISSUE THREAD

**Issue by Jmallone** [PiecePaperCode/pyogame2#16]
hi dude, i loved this work, you are amazing

well, [in this page ](https://github.com/PiecePaperCode/pyogame2/wiki/Code-Snippets#build-mines-routine)
 
change 
`res = empire.get_resources(id)`
 for
`resources = empire.get_resources(id)`

so that the code below is right.

` if resources.energy < 0 and not supply.solar_plant.is_possible:`

**Comment by PiecePaperCode** [comment]
hi man
Nice hint. 
i need to do the reverse because resources is already used.
`from pyogame2.constants import resources`

so doing
`res = empire.get_resources(id)`
`if res.energy < 0 and not supply.solar_plant.is_possible:`

will do the trick
