### ISSUE TITLE
Logout not working as expected

### ISSUE THREAD

**Issue by sHooPmyWooP** [PiecePaperCode/pyogame2#25]
When using logout() the expected result would be that requests in that session don't return a result or raise an exception. Nontheless even after logout it seems to be possible to query the server. Possibly OGame specific logic, but maybe worth looking into.

**Comment by PiecePaperCode** [comment]
Did you changed something?
logout returns exit() this will terminate your python programm. Even with no exit() return i cant make calls anymore. some functions (planet id, speed) are cachet.

```python
    def logout(self):
        self.session.get(self.index_php + 'page=logout')
        return exit()
```
```python
    def logout(self):
        self.session.get('https://s{}-{}.ogame.gameforge.com/game/index.php?page=logout'
                         .format(self.server_number, self.server_language))
        return exit()
```
i cant reproduce your error

**Comment by PiecePaperCode** [comment]
after PM problem got resolved
